
DROP TABLE IF EXISTS NASHVILE
SELECT * FROM NASHVILE

SELECT *INTO NASHVILE FROM NASHVILE_COPY

SELECT * FROM NASHVILE_COPY WHERE PROPERTYADDRESS IS NULL

--GETTING COLUMN NAMES

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'NASHVILE';


--STANDARDIZE DATE FORMAT ALTER THE DATATYPE OF COLUMN SALEDATE
ALTER TABLE NASHVILE
ALTER COLUMN SALEDATE DATE

--POPULATE PROPERTY ADDRESS

SELECT A.[UniqueID ],A.ParcelID,A.PropertyAddress,
       B.[UniqueID ],B.ParcelID,B.PropertyAddress 
	   FROM NASHVILE AS A INNER JOIN NASHVILE  AS B
ON A.ParcelID=B.ParcelID AND A.[UniqueID ]!=B.[UniqueID ]
WHERE A.PropertyAddress IS NULL


UPDATE A SET PROPERTYADDRESS=ISNULL(A.PROPERTYADDRESS,B.PROPERTYADDRESS )
FROM NASHVILE AS A INNER JOIN NASHVILE  AS B
ON A.ParcelID=B.ParcelID AND A.[UniqueID ]!=B.[UniqueID ]
WHERE A.PropertyAddress IS NULL

--CHECKING FOR THE NULLS AFTER UPDATING
SELECT * FROM nashvile WHERE PropertyAddress IS NULL

---SPLIT THE PROPERTYADDRESS ITNO ADDRESS AND CITY

SELECT SUBSTRING(PROPERTYADDRESS,1, CHARINDEX(',',PROPERTYADDRESS)-1)  AS PLOTNO,
       SUBSTRING(PROPERTYADDRESS,CHARINDEX(',',PROPERTYADDRESS)+1,LEN(PROPERTYADDRESS)) AS CITY

FROM NASHVILE

ALTER TABLE NASHVILE
ADD [PROPERTY SPLIT ADDRESS] NVARCHAR(255)

UPDATE NASHVILE
SET [PROPERTY SPLIT ADDRESS]=SUBSTRING(PROPERTYADDRESS,1, CHARINDEX(',',PROPERTYADDRESS)-1)

ALTER TABLE NASHVILE
ADD [PROPERTY SPLIT CITY] NVARCHAR(255)

UPDATE NASHVILE
SET [PROPERTY SPLIT CITY]=SUBSTRING(PROPERTYADDRESS,CHARINDEX(',',PROPERTYADDRESS)+1,LEN(PROPERTYADDRESS)) 

---BREAKING OWNERADDRESS INTO CITY,STATE AND ADDRESS

SELECT * FROM NASHVILE

SELECT OWNERADDRESS,
		PARSENAME(REPLACE(OWNERADDRESS,',','.'),3) AS ADDRESS, 
		PARSENAME(REPLACE(OWNERADDRESS,',','.'),2) AS CITY, 
		PARSENAME(REPLACE(OWNERADDRESS,',','.'),1) AS STATE
	    FROM NASHVILE

ALTER TABLE NASHVILE
ADD [OWNER SPLIT ADDRESS] NVARCHAR(255)

UPDATE NASHVILE
SET [OWNER SPLIT ADDRESS]=PARSENAME(REPLACE(OWNERADDRESS,',','.'),3)

ALTER TABLE NASHVILE
ADD [OWNER SPLIT CITY] NVARCHAR(255)

UPDATE NASHVILE
SET [OWNER SPLIT CITY]=PARSENAME(REPLACE(OWNERADDRESS,',','.'),2)

ALTER TABLE NASHVILE
ADD [OWNER SPLIT STATE] NVARCHAR(255)

UPDATE NASHVILE
SET [OWNER SPLIT STATE]=PARSENAME(REPLACE(OWNERADDRESS,',','.'),1)


--CHANGE Y AND N TO YES AND NO IN SOLDAS VACANT

SELECT DISTINCT(SOLDASVACANT) FROM NASHVILE

UPDATE NASHVILE SET SOLDASVACANT= CASE WHEN SOLDASVACANT='Y' THEN 'YES'
                                       WHEN SOLDASVACANT='N' THEN 'NO'
									   ELSE SOLDASVACANT
									   END 

---DELETE DUPLICATE RECORDS

SELECT * FROM NASHVILE

WITH CTE AS (
SELECT *,ROW_NUMBER()OVER(PARTITION BY PARCELID,
                                       LANDUSE,PROPERTYADDRESS,
									   SALEDATE,SALEPRICE,
									   LEGALREFERENCE,
									   SOLDASVACANT,
									   OWNERNAME 
                                       ORDER BY UNIQUEID ASC) AS RN 
FROM NASHVILE
) DELETE FROM CTE WHERE RN>1

---DROP UNUSED COLUMNS

ALTER TABLE NASHVILE
DROP COLUMN PROPERTYADDRESS,OWNERADDRESS